
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -GS" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -GS" CACHE STRING "" FORCE)

set(CROSS_TOOLCHAIN_FLAGS_NATIVE "-DLLVM_TOOL_LLDB_BUILD=OFF" CACHE STRING "")

