
if($ENV{EXHERBO})
  set(CMAKE_AR /usr/x86_64-unknown-linux-gnu/bin/llvm-ar CACHE FILEPATH "")
  set(CMAKE_C_COMPILER /usr/x86_64-unknown-linux-gnu/bin/clang CACHE FILEPATH "")
  set(CMAKE_CXX_COMPILER /usr/x86_64-unknown-linux-gnu/bin/clang++ CACHE FILEPATH "")
  set(CMAKE_LINKER /usr/x86_64-unknown-linux-gnu/bin/ld.lld CACHE FILEPATH "")
  set(CMAKE_RANLIB /usr/x86_64-unknown-linux-gnu/bin/llvm-ranlib CACHE FILEPATH "")
else()
  set(CMAKE_AR /usr/bin/llvm-ar CACHE FILEPATH "")
  set(CMAKE_C_COMPILER /usr/bin/clang CACHE FILEPATH "")
  set(CMAKE_CXX_COMPILER /usr/bin/clang++ CACHE FILEPATH "")
  set(CMAKE_LINKER /usr/bin/ld.lld CACHE FILEPATH "")
  set(CMAKE_RANLIB /usr/bin/llvm-ranlib CACHE FILEPATH "")
endif()

