
set(CMAKE_AR /usr/bin/ar CACHE FILEPATH "")
set(CMAKE_ASM_COMPILER /usr/bin/as CACHE FILEPATH "")
set(CMAKE_C_COMPILER /usr/bin/clang CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER /usr/bin/clang++ CACHE FILEPATH "")
set(CMAKE_LINKER /usr/bin/ld CACHE FILEPATH "")
set(CMAKE_RANLIB /usr/bin/ranlib CACHE FILEPATH "")

set(CMAKE_SYSTEM_VERSION "${CMAKE_HOST_SYSTEM_VERSION}" CACHE STRING "")
set(CMAKE_CROSSCOMPILING FALSE CACHE BOOL "")
